### ISSUE TITLE
Source code license?

### ISSUE THREAD

**Issue by Beirdo** [cweichen/pygn#10]
I see no license listed for this project.  As I understand it, technically, any code/art/whatever in the US (where Github is hosting your stuff) without a license defaults to "all rights reserved". This means that though the code is visible to be read, it is not "open source" in the sense of an OSI-approved license. Nor can anyone else take your code and modify it (or honestly, even just use it) because you still retain all of those rights. It's the license that grants people the right to fork/copy/modify your code.

Github has set up http://choosealicense.com/ to help project maintainers decide between various licensing options. If you just want your code to be open and don't mind how other people use it, look at MIT or Modified BSD. If you want something copyleft that will make sure that forks of your code continue to be shared with the community, go for the GPL.

**Comment by cweichen** [comment]
This is now licensed under MIT License
